# Generated by Django 4.0.3 on 2022-03-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeez', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(default=0, max_length=120),
        ),
    ]
